Twilio 4.0.0
rejvban/nestjs-twilio pull request #49
Opened 2023-01-24 22:05 UTC by luluhoc

## What

What changes are being made? (e.g. feature, bug, docs etc.)

## Why

Why are these changes necessary?

## How

How were these changes implemented?

## Checklist

Have you done all of these things?

- [ ] Documentation added
- [ ] Tests
- [ ] Typescript definitions updated
- [ ] Ready to be merged

2023-01-24 22:11 UTC, luluhoc commented
@rejvban You can do it as a pre-release as this is RC-5 of Twilio. THanks

2023-01-25 09:36 UTC, luluhoc commented
readme updated @rejvban

2023-01-26 20:08 UTC, luluhoc commented
@rejvban updated to 4.0.0 official version can you merge?

2023-01-29 21:00 UTC, rejvban requested changes

2023-01-29 21:00 UTC, lkaric commented on package.json
> +  },
```suggestion
  "engines": {
    "npm": "please-use-yarn",
    "yarn": ">=1.17.3",
    "node": ">=14.0.0"
  },
```

2023-01-29 21:00 UTC, lkaric commented on lib/utils/twilio.interface.ts
> +import type { ClientOpts } from 'twilio/dist/lib/base/BaseTwilio';
I try to keep the `type` imports at the bottom of the import sections

2023-01-29 21:11 UTC, luluhoc commented
@rejvban both resolved

2023-01-29 21:56 UTC, rejvban approved these changes

2023-01-29 21:56 UTC, merged